# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tomorectv3d', [dirname(__file__)])
        except ImportError:
            import _tomorectv3d
            return _tomorectv3d
        if fp is not None:
            try:
                _mod = imp.load_module('_tomorectv3d', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tomorectv3d = swig_import_helper()
    del swig_import_helper
else:
    import _tomorectv3d
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class tomorectv3d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, tomorectv3d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, tomorectv3d, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _tomorectv3d.new_tomorectv3d(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tomorectv3d.delete_tomorectv3d
    __del__ = lambda self : None;
    def itertvR(self, *args): return _tomorectv3d.tomorectv3d_itertvR(self, *args)
    def radonmany(self, *args): return _tomorectv3d.tomorectv3d_radonmany(self, *args)
    def radonmanyadj(self, *args): return _tomorectv3d.tomorectv3d_radonmanyadj(self, *args)
    def settheta(self, *args): return _tomorectv3d.tomorectv3d_settheta(self, *args)
    def itertvR_wrap(self, *args): return _tomorectv3d.tomorectv3d_itertvR_wrap(self, *args)
    def radon_wrap(self, *args): return _tomorectv3d.tomorectv3d_radon_wrap(self, *args)
    def radonadj_wrap(self, *args): return _tomorectv3d.tomorectv3d_radonadj_wrap(self, *args)
tomorectv3d_swigregister = _tomorectv3d.tomorectv3d_swigregister
tomorectv3d_swigregister(tomorectv3d)

# This file is compatible with both classic and new-style classes.


